version: '3.4'

services:
  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      #- ASPNETCORE_HTTPS_PORT="80443"
      #- ASPNETCORE_Kestrel__Certificates__Default__Password=1q2w3e4r
      #- ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/localhost.pfx
      #openssl pkcs12 -in ./localhost.pfx -clcerts -nokeys -out domain.crt
      #openssl pkcs12 -in ./localhost.pfx -nocerts -nodes -out domain.rsa
    ports:
      - "80"
      #- "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro