version: '3.4'

services:
   nginx:
    restart: unless-stopped
    image: nginx:stable
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/ssl/localhost.crt:/etc/ssl/certs/localhost.crt
      - ./data/nginx/ssl/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
      - web
    networks:
      - coronaglass-net

   web:
     container_name: coronaglass-web_1
     restart: unless-stopped
     image: ${DOCKER_REGISTRY-}coronaglass-web
     build:
       context: .
       dockerfile: Web/Dockerfile
     volumes:
      - ./logs/web:/app/logs
     networks:
      - coronaglass-net

networks:
    coronaglass-net:
      driver: bridge